//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRequestHeader
    {
        public ShippingRequestHeader()
        {
            this.ShippingRequestDetails = new HashSet<ShippingRequestDetail>();
        }
    
        public int ShipReqID { get; set; }
        public string CustomerPONum { get; set; }
        public string ConsignmentRef { get; set; }
        public string TemperatureID { get; set; }
        public string MeansOfTransportID { get; set; }
        public string CustomerAccountID { get; set; }
        public string PickupFromID { get; set; }
        public System.DateTime PickupDate { get; set; }
        public string PickupTime { get; set; }
        public string DeliverToID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public string DeliveryInstructions { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public bool ProcessedSuccessfully { get; set; }
        public string SAPOrderNumber { get; set; }
    
        public virtual ICollection<ShippingRequestDetail> ShippingRequestDetails { get; set; }
    }
}
