//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingRequestDetail
    {
        public int ShipReqDtlID { get; set; }
        public int ShipReqID { get; set; }
        public string MaterialNumber { get; set; }
        public decimal Quantity { get; set; }
        public string UnitOfMeasure { get; set; }
        public decimal NetWeight { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal Volume { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual ShippingRequestHeader ShippingRequestHeader { get; set; }
    }
}
