//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderImportClasses.SCTWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SCTWS.ZSD_CREATE_WEB_SO")]
    public interface ZSD_CREATE_WEB_SO {
        
        // CODEGEN: Generating message contract since the operation ZSD_CREATE_WEB_SALES_ORDER is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_CREATE_WEB_SO:ZSD_CREATE_WEB_SALES_ORD" +
            "ERRequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZSD_CREATE_WEB_SO:ZSD_CREATE_WEB_SALES_ORD" +
            "ERResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1 ZSD_CREATE_WEB_SALES_ORDER(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSD_CREATE_WEB_SO:ZSD_CREATE_WEB_SALES_ORD" +
            "ERRequest", ReplyAction="urn:sap-com:document:sap:rfc:functions:ZSD_CREATE_WEB_SO:ZSD_CREATE_WEB_SALES_ORD" +
            "ERResponse")]
        System.Threading.Tasks.Task<OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1> ZSD_CREATE_WEB_SALES_ORDERAsync(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_WEB_SALES_ORDER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] eT_RETURNField;
        
        private ZSD_WEB_SO_HEADER_S iS_SO_HEADERField;
        
        private ZSD_WEB_SO_ITEM_S[] iT_SO_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ZSD_WEB_SO_HEADER_S IS_SO_HEADER {
            get {
                return this.iS_SO_HEADERField;
            }
            set {
                this.iS_SO_HEADERField = value;
                this.RaisePropertyChanged("IS_SO_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_WEB_SO_ITEM_S[] IT_SO_ITEM {
            get {
                return this.iT_SO_ITEMField;
            }
            set {
                this.iT_SO_ITEMField = value;
                this.RaisePropertyChanged("IT_SO_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_WEB_SO_ITEM_S : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mATNRField;
        
        private decimal kWMENGField;
        
        private string mEINSField;
        
        private decimal nTGEWField;
        
        private decimal bRGEWField;
        
        private decimal vOLUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal KWMENG {
            get {
                return this.kWMENGField;
            }
            set {
                this.kWMENGField = value;
                this.RaisePropertyChanged("KWMENG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MEINS {
            get {
                return this.mEINSField;
            }
            set {
                this.mEINSField = value;
                this.RaisePropertyChanged("MEINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal NTGEW {
            get {
                return this.nTGEWField;
            }
            set {
                this.nTGEWField = value;
                this.RaisePropertyChanged("NTGEW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal BRGEW {
            get {
                return this.bRGEWField;
            }
            set {
                this.bRGEWField = value;
                this.RaisePropertyChanged("BRGEW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal VOLUM {
            get {
                return this.vOLUMField;
            }
            set {
                this.vOLUMField = value;
                this.RaisePropertyChanged("VOLUM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_WEB_SO_HEADER_S : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bSTKDField;
        
        private string bSTKD_EField;
        
        private string tEMPField;
        
        private string tRATYField;
        
        private string kUNAGField;
        
        private string sHIPFRField;
        
        private string bSTDKField;
        
        private string pICKUPField;
        
        private string sHIPTOField;
        
        private string vDATUField;
        
        private string dELCOField;
        
        private string dELIV_INSTRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BSTKD {
            get {
                return this.bSTKDField;
            }
            set {
                this.bSTKDField = value;
                this.RaisePropertyChanged("BSTKD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BSTKD_E {
            get {
                return this.bSTKD_EField;
            }
            set {
                this.bSTKD_EField = value;
                this.RaisePropertyChanged("BSTKD_E");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TEMP {
            get {
                return this.tEMPField;
            }
            set {
                this.tEMPField = value;
                this.RaisePropertyChanged("TEMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRATY {
            get {
                return this.tRATYField;
            }
            set {
                this.tRATYField = value;
                this.RaisePropertyChanged("TRATY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string KUNAG {
            get {
                return this.kUNAGField;
            }
            set {
                this.kUNAGField = value;
                this.RaisePropertyChanged("KUNAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SHIPFR {
            get {
                return this.sHIPFRField;
            }
            set {
                this.sHIPFRField = value;
                this.RaisePropertyChanged("SHIPFR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string BSTDK {
            get {
                return this.bSTDKField;
            }
            set {
                this.bSTDKField = value;
                this.RaisePropertyChanged("BSTDK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string PICKUP {
            get {
                return this.pICKUPField;
            }
            set {
                this.pICKUPField = value;
                this.RaisePropertyChanged("PICKUP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SHIPTO {
            get {
                return this.sHIPTOField;
            }
            set {
                this.sHIPTOField = value;
                this.RaisePropertyChanged("SHIPTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string VDATU {
            get {
                return this.vDATUField;
            }
            set {
                this.vDATUField = value;
                this.RaisePropertyChanged("VDATU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DELCO {
            get {
                return this.dELCOField;
            }
            set {
                this.dELCOField = value;
                this.RaisePropertyChanged("DELCO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DELIV_INSTR {
            get {
                return this.dELIV_INSTRField;
            }
            set {
                this.dELIV_INSTRField = value;
                this.RaisePropertyChanged("DELIV_INSTR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSD_CREATE_WEB_SALES_ORDERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] eT_RETURNField;
        
        private ZSD_WEB_SO_ITEM_S[] iT_SO_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSD_WEB_SO_ITEM_S[] IT_SO_ITEM {
            get {
                return this.iT_SO_ITEMField;
            }
            set {
                this.iT_SO_ITEMField = value;
                this.RaisePropertyChanged("IT_SO_ITEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_CREATE_WEB_SALES_ORDERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDER ZSD_CREATE_WEB_SALES_ORDER;
        
        public ZSD_CREATE_WEB_SALES_ORDERRequest() {
        }
        
        public ZSD_CREATE_WEB_SALES_ORDERRequest(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDER ZSD_CREATE_WEB_SALES_ORDER) {
            this.ZSD_CREATE_WEB_SALES_ORDER = ZSD_CREATE_WEB_SALES_ORDER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSD_CREATE_WEB_SALES_ORDERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse ZSD_CREATE_WEB_SALES_ORDERResponse;
        
        public ZSD_CREATE_WEB_SALES_ORDERResponse1() {
        }
        
        public ZSD_CREATE_WEB_SALES_ORDERResponse1(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse ZSD_CREATE_WEB_SALES_ORDERResponse) {
            this.ZSD_CREATE_WEB_SALES_ORDERResponse = ZSD_CREATE_WEB_SALES_ORDERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZSD_CREATE_WEB_SOChannel : OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZSD_CREATE_WEB_SOClient : System.ServiceModel.ClientBase<OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO>, OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO {
        
        public ZSD_CREATE_WEB_SOClient() {
        }
        
        public ZSD_CREATE_WEB_SOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZSD_CREATE_WEB_SOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_CREATE_WEB_SOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZSD_CREATE_WEB_SOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1 OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO.ZSD_CREATE_WEB_SALES_ORDER(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest request) {
            return base.Channel.ZSD_CREATE_WEB_SALES_ORDER(request);
        }
        
        public OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse ZSD_CREATE_WEB_SALES_ORDER(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDER ZSD_CREATE_WEB_SALES_ORDER1) {
            OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest inValue = new OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest();
            inValue.ZSD_CREATE_WEB_SALES_ORDER = ZSD_CREATE_WEB_SALES_ORDER1;
            OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1 retVal = ((OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO)(this)).ZSD_CREATE_WEB_SALES_ORDER(inValue);
            return retVal.ZSD_CREATE_WEB_SALES_ORDERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1> OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO.ZSD_CREATE_WEB_SALES_ORDERAsync(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest request) {
            return base.Channel.ZSD_CREATE_WEB_SALES_ORDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERResponse1> ZSD_CREATE_WEB_SALES_ORDERAsync(OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDER ZSD_CREATE_WEB_SALES_ORDER) {
            OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest inValue = new OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SALES_ORDERRequest();
            inValue.ZSD_CREATE_WEB_SALES_ORDER = ZSD_CREATE_WEB_SALES_ORDER;
            return ((OrderImportClasses.SCTWS.ZSD_CREATE_WEB_SO)(this)).ZSD_CREATE_WEB_SALES_ORDERAsync(inValue);
        }
    }
}
